//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MouseImitator.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MouseImitator.Application.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mis.
        /// </summary>
        internal static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Save Files (*.mis)|*.mis.
        /// </summary>
        internal static string files_filter {
            get {
                return ResourceManager.GetString("files_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string idle {
            get {
                return ResourceManager.GetString("idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Mode.
        /// </summary>
        internal static string mode_editor {
            get {
                return ResourceManager.GetString("mode_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imitator Mode.
        /// </summary>
        internal static string mode_imitator {
            get {
                return ResourceManager.GetString("mode_imitator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Replays.
        /// </summary>
        internal static string no_replays {
            get {
                return ResourceManager.GetString("no_replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string recording {
            get {
                return ResourceManager.GetString("recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        internal static string replay {
            get {
                return ResourceManager.GetString("replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaying.
        /// </summary>
        internal static string replaying {
            get {
                return ResourceManager.GetString("replaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replays: {0}.
        /// </summary>
        internal static string replays_progress {
            get {
                return ResourceManager.GetString("replays_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string steps_progress {
            get {
                return ResourceManager.GetString("steps_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string stop_recording {
            get {
                return ResourceManager.GetString("stop_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Replaying.
        /// </summary>
        internal static string stop_replaying {
            get {
                return ResourceManager.GetString("stop_replaying", resourceCulture);
            }
        }
    }
}
